config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  devise_for :users
  resources :materials_has_obras
  resources :materials
  resources :brands
  resources :categories
  resources :obras
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/obra.rb
class Obra < ApplicationRecord
has_many :material
has_many :materials_has_obras
end

app/controllers/obras_controller.rb
class ObrasController < ApplicationController
  before_action :set_obra, only: %i[ show edit update destroy ]

  # GET /obras or /obras.json
  def index
    @obras = Obra.all
  end

  # GET /obras/1 or /obras/1.json
  def show
  end

  # GET /obras/new
  def new
    @obra = Obra.new
  end

  # GET /obras/1/edit
  def edit
  end

  # POST /obras or /obras.json
  def create
    @obra = Obra.new(obra_params)

    respond_to do |format|
      if @obra.save
        format.html { redirect_to obra_url(@obra), notice: "Obra was successfully created." }
        format.json { render :show, status: :created, location: @obra }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /obras/1 or /obras/1.json
  def update
    respond_to do |format|
      if @obra.update(obra_params)
        format.html { redirect_to obra_url(@obra), notice: "Obra was successfully updated." }
        format.json { render :show, status: :ok, location: @obra }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obras/1 or /obras/1.json
  def destroy
    @obra.destroy

    respond_to do |format|
      format.html { redirect_to obras_url, notice: "Obra was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_obra
      @obra = Obra.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def obra_params
      params.require(:obra).permit(:nombre, :fecha_inicio, :fecha_fin, :costo, :calle, :numero, :ciudad, :estado, :codigo_postal)
    end
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/views/obras/_form.html.erb
<%= form_with(model: obra) do |form| %>
  <% if obra.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(obra.errors.count, "error") %> prohibited this obra from being saved:</h2>

      <ul>
        <% obra.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :fecha_inicio, style: "display: block" %>
    <%= form.date_field :fecha_inicio %>
  </div>

  <div>
    <%= form.label :fecha_fin, style: "display: block" %>
    <%= form.date_field :fecha_fin %>
  </div>

  <div>
    <%= form.label :costo, style: "display: block" %>
    <%= form.number_field :costo %>
  </div>

  <div>
    <%= form.label :calle, style: "display: block" %>
    <%= form.text_field :calle %>
  </div>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.text_field :numero %>
  </div>

  <div>
    <%= form.label :ciudad, style: "display: block" %>
    <%= form.text_field :ciudad %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.text_field :estado %>
  </div>

  <div>
    <%= form.label :codigo_postal, style: "display: block" %>
    <%= form.text_field :codigo_postal %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/obras/_obra.html.erb
<div id="<%= dom_id obra %>">
  <p>
    <strong>Nombre:</strong>
    <%= obra.nombre %>
  </p>

  <p>
    <strong>Fecha inicio:</strong>
    <%= obra.fecha_inicio %>
  </p>

  <p>
    <strong>Fecha fin:</strong>
    <%= obra.fecha_fin %>
  </p>

  <p>
    <strong>Costo:</strong>
    <%= obra.costo %>
  </p>

  <p>
    <strong>Calle:</strong>
    <%= obra.calle %>
  </p>

  <p>
    <strong>Numero:</strong>
    <%= obra.numero %>
  </p>

  <p>
    <strong>Ciudad:</strong>
    <%= obra.ciudad %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= obra.estado %>
  </p>

  <p>
    <strong>Codigo postal:</strong>
    <%= obra.codigo_postal %>
  </p>

</div>

app/views/obras/edit.html.erb
<h1>Editing obra</h1>

<%= render "form", obra: @obra %>

<br>

<div>
  <%= link_to "Show this obra", @obra %> |
  <%= link_to "Back to obras", obras_path %>
</div>

app/views/obras/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Obras</h1>

<div id="obras">
  <% @obras.each do |obra| %>
    <%= render obra %>
    <p>
      <%= link_to "Show this obra", obra %>
    </p>
  <% end %>
</div>

<%= link_to "New obra", new_obra_path %>

app/views/obras/new.html.erb
<h1>New obra</h1>

<%= render "form", obra: @obra %>

<br>

<div>
  <%= link_to "Back to obras", obras_path %>
</div>

app/views/obras/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @obra %>

<div>
  <%= link_to "Edit this obra", edit_obra_path(@obra) %> |
  <%= link_to "Back to obras", obras_path %>

  <%= button_to "Destroy this obra", @obra, method: :delete %>
</div>