config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  devise_for :users
  resources :materials_has_obras
  resources :materials
  resources :brands
  resources :categories
  resources :obras
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/materials_has_obra.rb
class MaterialsHasObra < ApplicationRecord
belongs_to :material
belongs_to :brand
end

app/controllers/materials_has_obras_controller.rb
class MaterialsHasObrasController < ApplicationController
  before_action :set_materials_has_obra, only: %i[ show edit update destroy ]

  # GET /materials_has_obras or /materials_has_obras.json
  def index
    @materials_has_obras = MaterialsHasObra.all
  end

  # GET /materials_has_obras/1 or /materials_has_obras/1.json
  def show
  end

  # GET /materials_has_obras/new
  def new
    @materials_has_obra = MaterialsHasObra.new
  end

  # GET /materials_has_obras/1/edit
  def edit
  end

  # POST /materials_has_obras or /materials_has_obras.json
  def create
    @materials_has_obra = MaterialsHasObra.new(materials_has_obra_params)

    respond_to do |format|
      if @materials_has_obra.save
        format.html { redirect_to materials_has_obra_url(@materials_has_obra), notice: "Materials has obra was successfully created." }
        format.json { render :show, status: :created, location: @materials_has_obra }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @materials_has_obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials_has_obras/1 or /materials_has_obras/1.json
  def update
    respond_to do |format|
      if @materials_has_obra.update(materials_has_obra_params)
        format.html { redirect_to materials_has_obra_url(@materials_has_obra), notice: "Materials has obra was successfully updated." }
        format.json { render :show, status: :ok, location: @materials_has_obra }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @materials_has_obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials_has_obras/1 or /materials_has_obras/1.json
  def destroy
    @materials_has_obra.destroy

    respond_to do |format|
      format.html { redirect_to materials_has_obras_url, notice: "Materials has obra was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materials_has_obra
      @materials_has_obra = MaterialsHasObra.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def materials_has_obra_params
      params.require(:materials_has_obra).permit(:material_id, :brand_id, :cantidad)
    end
end

app/helpers/materials_has_obras_helper.rb
module MaterialsHasObrasHelper
end

app/views/materials_has_obras/_form.html.erb
<%= form_with(model: materials_has_obra) do |form| %>
  <% if materials_has_obra.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(materials_has_obra.errors.count, "error") %> prohibited this materials_has_obra from being saved:</h2>

      <ul>
        <% materials_has_obra.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :material_id, style: "display: block" %>
    <%= form.text_field :material_id %>
  </div>

  <div>
    <%= form.label :brand_id, style: "display: block" %>
    <%= form.text_field :brand_id %>
  </div>

  <div>
    <%= form.label :cantidad, style: "display: block" %>
    <%= form.number_field :cantidad %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/materials_has_obras/_materials_has_obra.html.erb
<div id="<%= dom_id materials_has_obra %>">
  <p>
    <strong>Material:</strong>
    <%= materials_has_obra.material_id %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= materials_has_obra.brand_id %>
  </p>

  <p>
    <strong>Cantidad:</strong>
    <%= materials_has_obra.cantidad %>
  </p>

</div>

app/views/materials_has_obras/edit.html.erb
<h1>Editing materials has obra</h1>

<%= render "form", materials_has_obra: @materials_has_obra %>

<br>

<div>
  <%= link_to "Show this materials has obra", @materials_has_obra %> |
  <%= link_to "Back to materials has obras", materials_has_obras_path %>
</div>

app/views/materials_has_obras/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Materials has obras</h1>

<div id="materials_has_obras">
  <% @materials_has_obras.each do |materials_has_obra| %>
    <%= render materials_has_obra %>
    <p>
      <%= link_to "Show this materials has obra", materials_has_obra %>
    </p>
  <% end %>
</div>

<%= link_to "New materials has obra", new_materials_has_obra_path %>

app/views/materials_has_obras/new.html.erb
<h1>New materials has obra</h1>

<%= render "form", materials_has_obra: @materials_has_obra %>

<br>

<div>
  <%= link_to "Back to materials has obras", materials_has_obras_path %>
</div>

app/views/materials_has_obras/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @materials_has_obra %>

<div>
  <%= link_to "Edit this materials has obra", edit_materials_has_obra_path(@materials_has_obra) %> |
  <%= link_to "Back to materials has obras", materials_has_obras_path %>

  <%= button_to "Destroy this materials has obra", @materials_has_obra, method: :delete %>
</div>